language: python
install: pip install tox --use-mirrors
env:
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pep8

script: tox -e $TOX_ENV
notifications:
  email:
    - jamie.painter@rackspace.com
    - xuan.yu@rackspace.com
